#!/bin/bash

npm install --registry https://registry.npmjs.org/
gitbook install
grunt build
rm ./build/package.json
rm ./build/manifest.yml
rm ./build/Gruntfile.json
rm ./build/pom.xml
mvn clean package deploy -U
cf push
